--liquibase formatted sql
--changeset C7V5Z6:5

CREATE TABLE IF NOT EXISTS aae_gov_marketing.sfdc_campaign (
ACCOMMODATIONS__C                                           VARCHAR(255), 
ACTUAL_ATTENDENCE__C                                        DECIMAL(18, 2), 
AGENT__C                                                    VARCHAR(255), 
AGENT_AGENCY__C                                             VARCHAR(255), 
AGENT_BSR__C                                                VARCHAR(255), 
AGENT_WRITING_ID__C                                         VARCHAR(1000), 
BACKEND_CAMPAIGN_ID__C                                      VARCHAR(255), 
BACKEND_CANCELLATION_DATE__C                                TIMESTAMP, 
BACKEND_THUB_UPDATED_TIME__C                                TIMESTAMP, 
Backend_User__c                                             VARCHAR(255), 
BSR_MANAGER__C                                              VARCHAR(255), 
CAMPAIGN_ID__C                                              VARCHAR(255), 
CAMPAIGN_ID_DO_NOT_USE__C                                   DECIMAL(18, 2), 
CANCELLATION_DATE__C                                        TIMESTAMP, 
CANCELLATION_REASON__C                                      VARCHAR(255), 
CANCELLATION_REASON_OTHER__C                                VARCHAR(255), 
CONTACT_PHONE__C                                            VARCHAR(255), 
CONTRACT__C                                                 VARCHAR(255), 
CONTRACT_NAME__C                                            VARCHAR(255), 
CONTRACT_NAME_OLD__C                                        VARCHAR(255), 
CONTRACT_OLD__C                                             VARCHAR(255), 
COST_OF_FOOD_BEVERAGES__C                                   DECIMAL(18, 2), 
COST_OF_GIFTS_ACTIVITIES__C                                 DECIMAL(18, 2), 
COST_PER_PERSON_OF_THE_FOOD_BEVERAGE__C                     DECIMAL(18, 2), 
COST_PER_PERSON_OF_THE_GIFT_ACTIVITY__C                     DECIMAL(18, 2), 
CREATIVE__C                                                 VARCHAR(255), 
Custom_Approver__c                                          VARCHAR(255), 
DATE_RESCHEDULED__C                                         TIMESTAMP, 
DNIS__C                                                     VARCHAR(255), 
ESTIMATED_ATTENDANCE__C                                     DECIMAL(18, 2), 
EVENT_CONTACT__C                                            VARCHAR(255), 
EVENT_SUBMITTED_AFTER_15TH_OF_THE_MONTH__C                  TINYINT, 
EVENT_TIME__C                                               VARCHAR(255), 
EVENT_TYPE__C                                               VARCHAR(255), 
FACILITY_TYPE__C                                            VARCHAR(1000), 
FOOD_BEVERAGES_OFFERED__C                                   VARCHAR(255), 
FOOD_BEVERAGES_OFFERED_COMPLIANT__C                         VARCHAR(255), 
GIFTS_ACTIVITIES_OFFERED__C                                 VARCHAR(255), 
GIFTS_OFFERED_COMPLIANT__C                                  VARCHAR(255), 
KIT_TYPE__C                                                 VARCHAR(255), 
LANGUAGE__C                                                 VARCHAR(255), 
LEAD_DRIVER__C                                              VARCHAR(255), 
MARKET__C                                                   VARCHAR(255), 
MCE_ID__C                                                   VARCHAR(255), 
MICROMARKET__C                                              VARCHAR(255), 
NPN__C                                                      VARCHAR(1000), 
OTHER_LANGUAGE__C                                           VARCHAR(255), 
PRESENTATION_LANGUAGE__C                                    VARCHAR(255), 
PRESENTATION_LANGUAGE_IF_OTHER__C                           VARCHAR(255), 
PROJECT_CODE__C                                             VARCHAR(255), 
PROVIDER__C                                                 VARCHAR(255), 
QUALIFIED_AGENT__C                                          VARCHAR(255), 
REGION__C                                                   VARCHAR(255), 
RESCHEDULE__C                                               TINYINT, 
SOURCESYSTEMID__C                                           VARCHAR(255), 
TFN__C                                                      VARCHAR(255), 
THUB_RESPONSE_MESSAGE__C                                    VARCHAR(1000), 
THUB_STATUS_CODE__C                                         DECIMAL(18, 2), 
UUID__C                                                     VARCHAR(255), 
VENUE_ADDRESS1__C                                           VARCHAR(255), 
VENUE_ADDRESS2__C                                           VARCHAR(255), 
VENUE_ADDRESS__C                                            VARCHAR(255), 
VENUE_CAPACITY__C                                           DECIMAL(18, 2), 
VENUE_CITY__C                                               VARCHAR(255), 
VENUE_NAME__C                                               VARCHAR(255), 
VENUE_PHONE__C                                              VARCHAR(255), 
VENUE_STATE__C                                              VARCHAR(255), 
VENUE_ZIP_CODE__C                                           VARCHAR(255), 
VLOCITY_INS__CAMPAIGNCONTENTDOCUMENTID__C                   VARCHAR(255), 
VLOCITY_INS__CONTENTDOCUMENTTITLE__C                        VARCHAR(255), 
VLOCITY_INS__EMAILTEMPLATE__C                               VARCHAR(255), 
VLOCITY_INS__FOLLOWUPTO__C                                  VARCHAR(255), 
VLOCITY_INS__LINEOFBUSINESS__C                              VARCHAR(255), 
VLOCITY_INS__MASSEMAILCONTENT__C                            VARCHAR(1000), 
VLOCITY_INS__MASSEMAILSUBJECT__C                            VARCHAR(1000), 
VLOCITY_INS__PROCESSLANGUAGE__C                             VARCHAR(255), 
VLOCITY_INS__PROCESSPREFILLBUNDLE__C                        VARCHAR(255), 
VLOCITY_INS__PROCESSSUBTYPE__C                              VARCHAR(255), 
VLOCITY_INS__PROCESSTYPE__C                                 VARCHAR(255), 
ACTUALCOST                                                  DECIMAL(18, 2), 
AMOUNTALLOPPORTUNITIES                                      DECIMAL(18, 2), 
AMOUNTWONOPPORTUNITIES                                      DECIMAL(18, 2), 
BUDGETEDCOST                                                DECIMAL(18, 2), 
CAMPAIGNMEMBERRECORDTYPEID                                  VARCHAR(255), 
CREATEDBYID                                                 VARCHAR(255), 
CREATEDDATE                                                 TIMESTAMP, 
DESCRIPTION                                                 VARCHAR(1000), 
ENDDATE                                                     TIMESTAMP, 
EXPECTEDRESPONSE                                            DECIMAL(18, 2), 
EXPECTEDREVENUE                                             DECIMAL(18, 2), 
HIERARCHYACTUALCOST                                         DECIMAL(18, 2), 
HIERARCHYAMOUNTALLOPPORTUNITIES                             DECIMAL(18, 2), 
HIERARCHYAMOUNTWONOPPORTUNITIES                             DECIMAL(18, 2), 
HIERARCHYBUDGETEDCOST                                       DECIMAL(18, 2), 
HIERARCHYEXPECTEDREVENUE                                    DECIMAL(18, 2), 
HIERARCHYNUMBEROFCONTACTS                                   INTEGER, 
HIERARCHYNUMBEROFCONVERTEDLEADS                             INTEGER, 
HIERARCHYNUMBEROFLEADS                                      INTEGER, 
HIERARCHYNUMBEROFOPPORTUNITIES                              INTEGER, 
HIERARCHYNUMBEROFRESPONSES                                  INTEGER, 
HIERARCHYNUMBEROFWONOPPORTUNITIES                           INTEGER, 
HIERARCHYNUMBERSENT                                         DECIMAL(18, 2), 
ID                                                          VARCHAR(255), 
ISACTIVE                                                    TINYINT, 
ISDELETED                                                   TINYINT, 
LASTACTIVITYDATE                                            TIMESTAMP, 
LASTMODIFIEDBYID                                            VARCHAR(255), 
LASTMODIFIEDDATE                                            TIMESTAMP, 
LASTREFERENCEDDATE                                          TIMESTAMP, 
LASTVIEWEDDATE                                              TIMESTAMP, 
NAME_RW                                                     VARCHAR(255), 
NUMBEROFCONTACTS                                            INTEGER, 
NUMBEROFCONVERTEDLEADS                                      INTEGER, 
NUMBEROFLEADS                                               INTEGER, 
NUMBEROFOPPORTUNITIES                                       INTEGER,
NUMBEROFRESPONSES                                           INTEGER, 
NUMBEROFWONOPPORTUNITIES                                    INTEGER, 
NUMBERSENT                                                  DECIMAL(18, 2), 
OWNERID                                                     VARCHAR(255), 
PARENTID                                                    VARCHAR(255), 
RECORDTYPEID                                                VARCHAR(255), 
STARTDATE                                                   TIMESTAMP, 
STATUS                                                      VARCHAR(255), 
SYSTEMMODSTAMP                                              TIMESTAMP, 
TYPE_RW                                                     VARCHAR(255), 
SubMarket__c                                                VARCHAR(255), 
TOUCH__C                                                    VARCHAR(255), 
CATEGORY__C                                                 VARCHAR(255), 
URL__C                                                      VARCHAR(255), 
URL_SPANISH__C                                              VARCHAR(255), 
CM_Product_Type__c                                          VARCHAR(10), 
CM_TIMESTAMP__c                                             TIMESTAMP, 
CM_Campaign_Group__c                                        VARCHAR(155), 
CM_Campaign_Program__c                                      VARCHAR(80), 
CM_Case_Id__c                                               VARCHAR(20), 
CM_CID__c                                                   VARCHAR(20), 
CM_Event_ID__c                                              VARCHAR(20), 
CM_Fulfillment__c                                           VARCHAR(225), 
CM_Kit_Description__c                                       VARCHAR(225), 
CM_Macromarket__c                                           VARCHAR(50), 
CM_Phone_Campaign__c                                        VARCHAR(80), 
CM_Print_Code__c                                            VARCHAR(225), 
CM_STATUS_OF_CAMPAIGN_LOAD__c                               VARCHAR(50), 
CM_Status_of_TFA__c                                         VARCHAR(50), 
Application_Submitted__c                                    TINYINT, 
Number_Interactions__c                                      INTEGER, 
In_Person_Virtual__c                                        TINYINT, 
Event_Date__c                                               TIMESTAMP, 
Event_Endtime__c                                            TIMESTAMP, 
Event_Starttime__c                                          TIMESTAMP, 
MSA_Completion_Date__c                                      TIMESTAMP, 
MSA_Submission_Date__c                                      TIMESTAMP, 
Outbound_Campaign_Finish_Date__c                            TIMESTAMP, 
Outbound_Campaign_Start__c                                  TIMESTAMP, 
Outbound_Campaign_Start_Date__c                             TIMESTAMP, 
SOW_Completion_Date__c                                      TIMESTAMP, 
SOW_Submission_Date__c                                      TIMESTAMP, 
Store_Number__c                                             INTEGER, 
Store__c                                                    VARCHAR(255), 
Agent_Phone__c                                              VARCHAR(40), 
Business_Unit__c                                            VARCHAR(20), 
Campaign_Area__c                                            VARCHAR(20), 
Campaign_Population__c                                      VARCHAR(30), 
Agent_Email__c                                              VARCHAR(255), 
Agent_Name__c                                               VARCHAR(1300), 
Business_Owner__c                                           VARCHAR(255), 
CampaignImageId                                             VARCHAR(255), 
County__c                                                   VARCHAR(255), 
End_Time__c                                                 VARCHAR(30), 
Event_Sub_Type__c                                           VARCHAR(20), 
Existing_Data__c                                            VARCHAR(10), 
Frequency_of_Data__c                                        VARCHAR(30), 
Has_A_TFN_Been_Created__c                                   VARCHAR(15), 
Location_Type__c                                            VARCHAR(255), 
MSA__c                                                      VARCHAR(255), 
MSA_Contract_Number__c                                      VARCHAR(255), 
Other_Venue_Type__c                                         VARCHAR(255), 
Outbound_Campaign_Description__c                            VARCHAR(255), 
Outbound_Campaign_Frequency__c                              VARCHAR(30), 
Outbound_Campaign_Id__c                                     VARCHAR(1300), 
Outbound_Campaign_Status__c                                 VARCHAR(30), 
Outbound_Campaign_Type__c                                   VARCHAR(20), 
Outbound_Campaign_Year__c                                   VARCHAR(10), 
OutboundCompositeKey1__c                                    VARCHAR(255), 
Recurring__c                                                VARCHAR(10), 
Sample_Date__c                                              VARCHAR(10), 
SOW__c                                                      VARCHAR(20), 
SOW_Contract_Number__c                                      VARCHAR(255), 
Store_Manager_Name__c                                       VARCHAR(22), 
Store_Manager_Phone_Number__c                               VARCHAR(40), 
Type_of_Call__c                                             VARCHAR(30), 
Vendor__c                                                   VARCHAR(20), 
Vendor_Name__c                                              VARCHAR(20), 
Venue_Type__c                                               VARCHAR(30), 
CM_CSB_Orig_Campaign_CreatedDate__c                         TIMESTAMP, 
CM_Historical_Last_Modified_Date__c                         TIMESTAMP, 
AUDITDATAID                                                 BIGINT NOT NULL, 
SRC_DATA_KEY                                                SMALLINT NOT NULL, 
LOAD_DTTS                                                   TIMESTAMP,
PRIMARY KEY (ID) -- NOT UNIQUE INDEX
) 
USING DELTA 
TBLPROPERTIES (delta.enableChangeDataCapture=true,delta.autooptimize.optimizewrite=true,delta.minReaderVersion='2',delta.minWriterVersion='5',delta.columnMapping.mode='name');
-- rollback DROP TABLE aae_gov_marketing.sfdc_campaign; 
