--liquibase formatted sql

 --changeset C7V5Z6:4
CREATE TABLE IF NOT EXISTS aae_gov_marketing.sfdc_do_not_contact__c (
ACTIVE__C TINYINT, 
BACKEND_COMMA__C VARCHAR(255), 
BACKEND_LEAD_EMAIL__C VARCHAR(255), 
BACKEND_LEAD_ID__C VARCHAR(255), 
DNC_LEAD_LINK__C VARCHAR(255), 
END_DATE__C TIMESTAMP, 
LEAD__C VARCHAR(255), 
LEAD_DNC__C VARCHAR(255), 
LEADFIRSTNAME__C VARCHAR(255), 
LEADLASTNAME__C VARCHAR(255), 
MEMBER__C VARCHAR(255), 
METHOD__C VARCHAR(255), 
PARENTEMAIL__C VARCHAR(255), 
SOURCESYSTEMID__C VARCHAR(255), 
START_DATE__C TIMESTAMP, 
CREATEDBYID VARCHAR(255), 
CREATEDDATE TIMESTAMP, 
ID VARCHAR(255), 
ISDELETED TINYINT, 
LASTACTIVITYDATE TIMESTAMP, 
LASTMODIFIEDBYID VARCHAR(255), 
LASTMODIFIEDDATE TIMESTAMP, 
LASTREFERENCEDDATE TIMESTAMP, 
LASTVIEWEDDATE TIMESTAMP, 
NAME_RW VARCHAR(255), 
OWNERID VARCHAR(255), 
SYSTEMMODSTAMP TIMESTAMP, 
OPPORTUNITY__C VARCHAR(255), 
AUDITDATAID BIGINT NOT NULL, 
SRC_DATA_KEY SMALLINT NOT NULL, 
LOAD_DTTS TIMESTAMP,
PRIMARY KEY (ID) -- NOT UNIQUE INDEX
) 
USING DELTA 
TBLPROPERTIES (delta.enableChangeDataCapture=true,delta.autooptimize.optimizewrite=true,delta.minReaderVersion='2',delta.minWriterVersion='5',delta.columnMapping.mode='name');
-- rollback DROP TABLE aae_gov_marketing.sfdc_do_not_contact__c;  
